config/routes.rb
Rails.application.routes.draw do

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"

  get '/register' => "user#new"
  post '/register' => "user#create"

  root to: 'todos#index'

  resources 'todos'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :todos

  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      p "HIIIIIII"
      p session.inspect
      redirect_to todos_path
    else
      @errors = "Your email or password sucked"
      render :new
    end
  end

  def destroy
  session[:user_id] = nil
  redirect_to login_path
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = current_user.todos
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @new_todo = Todo.new(title: params[:todo][:title], description: params[:todo][:description], user_id: session[:user_id])
    if @new_todo.save
      respond_to do |format|
        format.json {render json: @new_todo}
      end
    else
      @errors = "You need to complete all of the fields"
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update_attributes(title: params[:todo][:title], description: params[:todo][:description])
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    respond_to do |format|
      format.json { render json: @todo }
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
include SessionsHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(email: params[:user][:email], password: params[:user][:password])
    if @user.save
      redirect_to login_path
    else
      @error = "Your username or password is invalid"
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find(session[:user_id])
  end

end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_create.html.erb
<%= form_for :todo do |t|%>

<%= t.label :title%>
<%= t.text_field :title%>

<%= t.label :description%>
<%= t.text_field :description%>

<%= t.submit "Submit" %>

<%end %>

app/views/todos/edit.html.erb
<h1> Edit your note </h1>

<%= form_for @todo do |t|%>
  <%= t.label "title" %>
  <%= t.text_field :title %>

  <%= t.label "description" %>
  <%= t.text_field :description %>

  <%= submit_tag "Update" %>
<% end %>

app/views/todos/index.html.erb
<h1>Your Todos: </h1>
<%= link_to 'Logout', logout_path, :method => :delete %>
<div class="list">
<ol>
  <% @todos.each do |todo| %>
    <div class="item" id="<%=todo.id%>"><li><%= todo.title %></br>
      <%= todo.description%></br>
      <div class="delete_button"> <%= link_to 'Delete', todo_path(todo), :method => :delete %> </div>
      <div class="edit_button"><%= link_to 'Edit', edit_todo_path(todo)%></div>
    </li></div>
  <% end %>
</ol>
</div>

<script id="new_todo" type="text/x-handlebars-template">
  <div class="item" id="{{data.id}}">
    <li>{{data.title}}</br>
    {{data.description}}</br>
    <div class="delete_button"><a href="/todos/{{data.id}}"> Delete </a></div>
    <div class="edit_button"><a href="/todos/{{data.id}}"> Edit </a></div>
    </li>
  </div>
</script>

<div id="new_todo_form" style="display:none">
  <%= render :partial => "create" %>
</div>

<div class="new_todo_link"><%= link_to 'New Todo', new_todo_path %></div>

app/views/todos/new.html.erb
<h1>Submit a new item</h1>

<%= form_for @todo do |t|%>

<%= t.label :title%>
<%= t.text_field :title%>

<%= t.label :description%>
<%= t.text_field :description%>

<%= t.submit "Submit" %>

<%end %>

app/views/user/new.html.erb
<h1>Sign Up!</h1>

<%= form_for @user, url: register_path do |u| %>
  <%= u.label :email %>
  <%= u.text_field :email %>

  <%= u.label :password %>
  <%= u.password_field :password %>

  <%= u.submit "Register" %>

<% end %>